---
# tasks file for nfs-server

#- name: Staring & enabling nfs-server
#  systemd:
#   name: "{{ item }}"    
#   state: started
#   enabled: yes
#   masked: no
#  become: yes
#  with_items:
#    - "{{ service_names }}"
  
- name: Installing packages on nfs-server
  dnf:
    name: "{{ dnf_packages }}"
    state: present
  become: yes  
  
- name: Creating mountable shared folders 1
  file: 
    path: "{{ shared_dir }}"
    state: directory
  become: yes
#Solo correr la primera vez
#- name: create folders share_dir 0
#  shell:  mkdir /mysql
#  become: yes

#- name:  create folders share_dir 1
#  shell:  mkdir {{ shared_dir[1] }}
#  become: yes

- name: Configure nfs server
  copy:
    dest: /etc/exports
    content: |
      {{ shared_dir[0] }} *(rw,no_root_squash,sync)
      {{ shared_dir[1] }} *(rw,no_root_squash,sync)
  become: yes

- name:  configuration of the /etc/exports file 
  shell: exportfs -r
  become: yes

- name: Firewall configuration
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  become: yes
  with_items:
    - "{{ firewall_serv }}"

- name: Enabling nfs-server
  shell: sudo systemctl enable nfs-server
  become: yes

- name: Staring nfs-server
  shell: sudo systemctl start nfs-server
  become: yes

- name: Restarting the Firewalld service 
  systemd:
    name: firewalld
    state: restarted
  become: yes
