 - name: "Turn off swap"
   shell: "swapoff -a"
   become: yes

- name: "Cmmenting Swap in /etc/fstab file"
  replace:
    path: /etc/fstab
    regexp: '^[^#](.*swap*)'
    replace: '#\1'  
   become: yes

- name:  Server reboot
  reboot:
  become: yes

- name: Enable the Kernel module br_netfilter
  modprobe:
    name: br_netfilter
    state: present
  become: yes

- name: Enable masquerade
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true
    zone: public
  become: yes

- name: Configure AllowZoneDrifting=no in firewalld
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting='
    line: "AllowZoneDrifting=no"
    state: present
  become: yes

- name: Enable ports used by the SDN Flannel for Azure 8285/UDP
  firewalld:
    port: 8285/udp
    permanent: true
    state: enabled
  become: yes

- name: Enable ports used by the SDN Flannel for Azure 8472/UDP
  firewalld:
    port: 8472/udp
    permanent: true
    state: enabled
  become: yes

- name: Enable and restart firewalld service
  systemd:
    name: firewalld
    state: restarted
    enabled: yes
    masked: no
  become: yes

- name: "Updating config file"
  copy: 
    dest: /etc/sysctl.d/k8s.conf
    content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
            net.ipv4.ip_forward                 = 1
  become: yes

- name: "Changing parameters for kernel"
  command: "sysctl --system"
  become: yes

- name: Add cri-o repo 1
  shell: dnf config-manager --add-repo=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
  args:
    creates: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
    warn: false
  become: yes

- name: Add cri-o repo 2
  shell: dnf config-manager --add-repo=https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
  args:
    creates: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    warn: false
  become: yes

- name: Installing packages on node
  dnf:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ packages }}" 
  
- name: Staring & enabling cri-o & kubelet on Node
  systemd:
   name: "{{ item }}"    
   state: started
   enabled: yes
   masked: no
  become: yes
  with_items: "{{ service_names }}"

- name: Creating a repository file for Kubernetes
  file:
   path: /etc/yum.repos.d/kubernetes.repo
   state: touch

- name: Set up the kubernetes repository.
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64     
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
  
- name: Set up the cri-o repository.
  copy:
    dest: /etc/modules-load.d/crio.conf
    content: |
        overlay
        br_netfilter
        

