---
# vars file for k8s_master
service_names:
        
  - cri-o
  - kubelet

ports:
- { port: "6443", proto: "tcp" }

ports_master:
- { port: "10250-10252", proto: "tcp" }
- { port: "10255", proto: "tcp" }
- { port: "2379-2380", proto: "tcp" }
- { port: "30000-32767", proto: "tcp" }

token_file: join_token

ad_addr: 192.168.1.44
cidr_v: 192.169.0.0/16
