---
# tasks file for k8s_worker

- name: "Allow Network Ports in Firewalld"
  firewalld:
    port: "{{ item }}" 
    state: enabled
    permanent: yes
    immediate: yes 
  become: yes
  with_items:
    - "{{ ports_slave }}"
  
- name: Reboot Firewalld service
  systemd:
    name: firewalld
    state: restarted
  become: yes
          
- name: Copying token to worker nodes
  copy: src={{ token_file }} dest=join_token

- name: Joining worker nodes with kubernetes master
  shell: "`grep -i 'kubeadm join' join_token`"
  become: yes

- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches
  
