---
# tasks file for k8s_master


- name: Installing packages on node
  dnf:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ packages }}" 
  
- name: Disabling SELinux state
  selinux:
    state: disabled

- name: Staring & enabling cri-o & kubelet on Node
  systemd:
   name: "{{ item }}"    
   state: started
   enabled: yes
   masked: no
   daemon_reload: yes
  become: yes
  with_items: "{{ service_names }}"

- name: Creating a repository file for Kubernetes
  file:
   path: /etc/yum.repos.d/kubernetes.repo
   state: touch

- name: Set up the kubernetes repository.
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64     
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
  

- name: "Updating config file"
  copy: 
    dest: /etc/sysctl.d/k8s.conf
    content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
            net.ipv4.ip_forward                 = 1
            
- name: "Turn off swap"
  shell: "swapoff -a"


- name: "Cmmenting Swap in /etc/fstab file"
  replace:
    path: /etc/fstab
    regexp: '^[^#](.*swap*)'
    replace: '#\1'  

- name: "Changing parameters for kernel"
  command: "sysctl --system"
  
  
- name: Set up the cri-o repository.
  copy:
    dest: /etc/modules-load.d/crio.conf
    content: |
        overlay
        br_netfilter
        
- name: Rebooting the server
  reboot:
    test_command: uptime

