
- name: "Allow Network Ports in Firewalld"
  firewalld:
    port: "{{item.port}}/{{item.proto}}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ ports_slave }}" 
          
- name: Copying token to worker nodes
  copy: src={{ token_file }} dest=join_token

- name: Joining worker nodes with kubernetes master
  shell: "`grep -i 'kubeadm join' join_token`"

- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches
  
- name: Restarting the Firewalld service 
  systemd:
    name: firewalld
    state: restarted
  become: yes
