---
# tasks file for nfs-server

- name: Staring & enabling nfs-server
  systemd:
   name: "{{ service_names }}"    
   state: started
   enabled: yes
   masked: no
  become: yes
  
- name: Installing packages on nfs-server
  dnf:
    name: "{{ dnf_packages }}"
    state: present
  become: yes  
  
- name: Creating mountable shared folders 1
  file: 
    path: "{{ shared_dir }}"
    state: directory
  become: yes

- name: Configure nfs server
  copy:
    dest: /etc/exports
    content: |
      {{ shared_dir[0] }} *(rw,no_root_squash,sync)
      {{ shared_dir[1] }} *(rw,no_root_squash,sync)
  become: yes

- name:  configuration of the /etc/exports file 
  shell: exportfs -r
  become: yes

- name: Firewall configuration
  firewalld:
    service: "{{ firewall_serv }}"
    permanent: true
    state: enabled
  become: yes
  
- name: Restarting the Firewalld service 
  systemd:
    name: firewalld
    state: restarted
  become: yes
