---
# tasks file for nfs-server


- name: Staring & enabling cri-o & kubelet on nfs-server
  systemd:
   name: "{{ item }}"    
   state: started
   enabled: yes
   masked: no
   force: yes
   daemon_reload: yes
  become: yes
  with_items: "{{ service_names }}"
  
- name: Installing packages on nfs-server
  dnf:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ dnf_packages }}"  
  
- name: Creating mountable shared folders
  file: 
    path: "{{ item }}"
    state: directory
  with_items: "{{ shared_dir }}"

- name: Configure nfs server
  copy:
    dest: /etc/exports
    content: |
      {{ shared_dir[0] }} *(rw,no_root_squash,sync)
      {{ shared_dir[1] }} *(rw,no_root_squash,sync)


- name:  configuration of the /etc/exports file 1
  shell: exportfs -r
  become: yes
  
- name:  configuration of the /etc/exports file 2
  shell: exportfs -s
  become: yes

- name: Firewall configuration
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  become: yes
  with_items: "{{ firewall_serv }}" 
  
- name: Restarting the Firewalld service 
  systemd:
    name: firewalld
    state: restarted
  become: yes
